/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fleet/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet Settings */
        get: operations["fleet_settings_api_fleet_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Funnel
         * @description Audience -> verdict -> LCM intake -> sent -> returned, from our own
         *     tables. OPERATOR auth: `detail=true` returns themes, mechanisms and
         *     org_ids, which the automation token has no business exporting — the
         *     machine gets /api/funnel/worklist instead.
         */
        get: operations["funnel_api_funnel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/funnel/worklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Funnel Worklist
         * @description The shipped touches as bare (run_id, pro_id) pairs — the n8n flow's
         *     work list. Shares the outcomes token because it is the same automation,
         *     and carries no theme/mechanism/org_id for the reason in funnel.worklist.
         */
        get: operations["funnel_worklist_api_funnel_worklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Outcomes
         * @description Observed messaging/app-usage outcomes, keyed by recommendation_id.
         *     See waypoint.outcomes for the attribution/backfill/idempotency logic.
         */
        post: operations["ingest_outcomes_api_outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Handoff */
        post: operations["create_handoff_api_runs__run_id__handoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kill Run */
        post: operations["kill_run_api_runs__run_id__kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandoffReceipt */
        HandoffReceipt: {
            /** Handoff Id */
            handoff_id: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "rejected" | "duplicate";
        };
        /** HandoffResponse */
        HandoffResponse: {
            /** Receipts */
            receipts: components["schemas"]["HandoffReceipt"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /** RunCreate */
        RunCreate: {
            /** Audience Query */
            audience_query: string;
            /** Audience Run */
            audience_run: string;
            /** Channels */
            channels: string[];
            /**
             * Journey Window
             * @default churn_risk
             * @enum {string}
             */
            journey_window: "churn_risk" | "churn_risk_open" | "onboarding" | "upsell";
            /** Loop Config */
            loop_config?: {
                [key: string]: number;
            } | null;
            /** Pro Ids */
            pro_ids: string[];
        };
        /** RunDetail */
        RunDetail: {
            /** Agents In Flight */
            agents_in_flight: number;
            /** Audience Query */
            audience_query: string;
            /** Audience Run */
            audience_run: string;
            /** Candidates */
            candidates: {
                [key: string]: unknown;
            }[];
            /** Channels */
            channels: string[];
            /** Config Version */
            config_version: string;
            /** Cost Limit Usd */
            cost_limit_usd: string;
            /** Cost Reserved Usd */
            cost_reserved_usd: string;
            /** Cost Spent Usd */
            cost_spent_usd: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Handoffs */
            handoffs: {
                [key: string]: unknown;
            }[];
            /** Id */
            id: string;
            /** Journey Window */
            journey_window: string;
            /** Killed */
            killed: boolean;
            /** Loop Config */
            loop_config: {
                [key: string]: number;
            };
            /** Measurements */
            measurements: {
                [key: string]: unknown;
            }[];
            /** Pro Ids */
            pro_ids: string[];
            /** Rounds */
            rounds: {
                [key: string]: unknown;
            }[];
            /** Stages */
            stages: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Stop Reason */
            stop_reason: string | null;
            /** Winners */
            winners: {
                [key: string]: unknown;
            }[];
        };
        /** RunView */
        RunView: {
            /** Audience Query */
            audience_query: string;
            /** Audience Run */
            audience_run: string;
            /** Channels */
            channels: string[];
            /** Config Version */
            config_version: string;
            /** Cost Limit Usd */
            cost_limit_usd: string;
            /** Cost Reserved Usd */
            cost_reserved_usd: string;
            /** Cost Spent Usd */
            cost_spent_usd: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Journey Window */
            journey_window: string;
            /** Loop Config */
            loop_config: {
                [key: string]: number;
            };
            /** Pro Ids */
            pro_ids: string[];
            /** Status */
            status: string;
            /** Stop Reason */
            stop_reason: string | null;
        };
        /**
         * TouchOutcomeIn
         * @description One observed-outcome record from an outcome source (n8n Iterable/Amplitude
         *     flow, or manual backfill).
         *
         *     TWO ways to name the touch, either is enough:
         *
         *     * `recommendation_id` — the Waypoint winner_id, echoed back under either
         *       spelling (`recommendation_id` or `row_id`).
         *     * `run_id` + `pro_id` — the NATURAL key, and the one that needs nothing
         *       stamped into a message: `uq_winners_run_pro` makes one run plus one pro
         *       exactly one winner. Both halves already cross the boundary on their own
         *       (the LCM intake batch IS the run id, and the Iterable recipient IS the
         *       pro_uuid), so an outcome is attributable without Waypoint ids ever
         *       entering Iterable.
         *
         *     `routing` is how a REAL send is told apart from a guardrailed test send that
         *     merely carries a real Pro's context. It must be `route-to-pro` for the
         *     record to count as evidence — see waypoint.outcomes.
         */
        TouchOutcomeIn: {
            /**
             * Channel
             * @default
             */
            channel: string;
            /** Clicked */
            clicked?: boolean | null;
            /** Delivered */
            delivered?: boolean | null;
            /**
             * Org Id
             * @default
             */
            org_id: string;
            /**
             * Pro Id
             * @default
             */
            pro_id: string;
            /**
             * Recommendation Id
             * @default
             */
            recommendation_id: string;
            /** Replied */
            replied?: boolean | null;
            /** Returned 14D */
            returned_14d?: boolean | null;
            /** Returned 30D */
            returned_30d?: boolean | null;
            /** Returned 7D */
            returned_7d?: boolean | null;
            /** Returned 90D */
            returned_90d?: boolean | null;
            /**
             * Routing
             * @default
             */
            routing: string;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Sent At */
            sent_at?: string | null;
            /** Source */
            source: string;
            /** Unsubscribed */
            unsubscribed?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fleet_settings_api_fleet_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    funnel_api_funnel_get: {
        parameters: {
            query?: {
                days?: number;
                detail?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    funnel_worklist_api_funnel_worklist_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_outcomes_api_outcomes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TouchOutcomeIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_handoff_api_runs__run_id__handoff_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HandoffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_run_api_runs__run_id__kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
